### ISSUE TITLE
SUP-1540 | Report Cycle Count Format Date เป็น MM/DD/YYYY

### ISSUE THREAD

**Issue by molog-auto** [molog-tech/project-ma-public#138]
Service Desk: SUP-1540

**Comment by KPatchanida** [comment]
### Service Desk: SUP-1540
**Detail Issue Follow ตามนี้ได้เลยค่ะ**

**Found Date / วันที่เจอ  :** 17-Aug-2024
**Found Version / เจอที่ version ไหน  :** On Saas (Version follow production Saas)
**Remark (Optional):** Standard Report Cycle count 01 / Standard Report Cycle count 02
**Step produce / รบกวนระบุ Step ที่เจอ  :**
1. Setting Parameter Report Cycle Count ส่วน Item ให้แสดง MFD DATE และ EXP DATE
2. เรียกดู report

**Actual result:**
- วันที่ที่แสดงในช่อง MFD DATE และ EXP DATE เป็น Format MM/DD/YYYY
- หากไม่ได้ทำการ Setting parameter ก่อน ในรายงานส่วนของชื่อคอลัมน์ขึ้น No Set

**Expected result:**
- วันที่ที่แสดงในช่อง MFD DATE และ EXP DATE เป็น Format DD/MM/YYYY
- หากไม่ได้ทำการ Setting parameter ก่อน ในรายงานส่วนของชื่อคอลัมน์ต้องแสดงเป็นค่าว่าง

**Attach picture:**
![Image](https://github.com/user-attachments/assets/4e6e110d-e6e4-410c-9f14-288caa3c38d2)

**Comment by guynatchanonML** [comment]
Test : **PASS** on Prod 
![Image](https://github.com/user-attachments/assets/08f93d79-d063-4ef7-bf2a-9f16b77e6377)
![Image](https://github.com/user-attachments/assets/80d414d9-a6c6-4174-8010-fa2df55ffe4c)
