### ISSUE TITLE
[SaaS] ระบบไม่มีการแจ้งเตือนวันหมดอายุการใช้งานระบบ

### ISSUE THREAD

**Issue by molog-auto** [molog-tech/project-ma-public#161]
[Customer : werkzeug]
SaaS:WMS เดิมระบบมีการแจ้งเตือนเมื่อใกล้ถึงวันหมดอายุ หรือการต่อ MA แต่ปัจจุบันลูกค้าแจ้งว่าไม่มีการแจ้งเตือน
รบกวนทีมตรวจสอบระบบให้ด้วยค่ะ

**Comment by guynatchanonML** [comment]
Test : **PASS** on Preprod

**Comment by guynatchanonML** [comment]
Test : **PASS** on Prod
![Image](https://github.com/user-attachments/assets/b0839945-d056-4724-acb8-0756f6abdeb1)
