### ISSUE TITLE
[Sailumtransport] สินค้าในระบบ ขึ้นสถานะสินค้าคืนดี เกิดจากอะไรครับ เพราะสินค้าถูกเบิกออกไปแล้ว

### ISSUE THREAD

**Issue by molog-auto** [molog-tech/project-ma-public#163]
Customer SaaS : Sailumtransport
User : watitsuerjinda@gmail.com
Pass :tee12345@

ปัญหาที่เจอ : สินค้าในระบบ ขึ้นสถานะสินค้าคืนดี เกิดจากอะไรครับ เพราะสินค้าถูกเบิกออกไปแล้ว
![image](https://github.com/user-attachments/assets/af7b9c10-be30-4dc1-a695-3477f4b65b0d)
![image](https://github.com/user-attachments/assets/10719bce-e4c2-4635-82f8-6de501dea8be)

**Comment by KPatchanida** [comment]
### **Update Issue Date:** 13.11.2024
Case นี้ไม่ใช่ bug ระบบนะคะ ลูกค้าทำการปล่อยสินค้าออกไป หลังจากนั้นในวันเดียวกันลูกค้าไปสร้างเอกสารคืนสินค้า รับคืนจนจบ process ทำให้สินค้าเข้า Inventory และสถานะเป็นสินค้าคืนดีค่ะ
